### ISSUE TITLE
cannot import name 'parse_rule' from 'werkzeug.routing' 

### ISSUE THREAD

**Issue by lawulu** [jgbustos/ml_rest_api#7]
I am using Mac and python3.9.
and got the same issue both from pycharm and cmd
```
Traceback (most recent call last):
  File "/Users/me/repo/github/ml_rest_api/ml_rest_api/app.py", line 10, in <module>
    from ml_rest_api.api.restx import api
  File "/Users/me/repo/github/ml_rest_api/ml_rest_api/api/restx.py", line 5, in <module>
    from flask_restx import Api
  File "/Users/me/.local/lib/python3.9/site-packages/flask_restx/__init__.py", line 5, in <module>
    from .api import Api  # noqa
  File "/Users/me/.local/lib/python3.9/site-packages/flask_restx/api.py", line 50, in <module>
    from .swagger import Swagger
  File "/Users/me/.local/lib/python3.9/site-packages/flask_restx/swagger.py", line 18, in <module>
    from werkzeug.routing import parse_rule
ImportError: cannot import name 'parse_rule' from 'werkzeug.routing' (/Users/me/.local/lib/python3.9/site-packages/werkzeug/routing/__init__.py)

```

After I downgraded the werkzeug and flask, it works:

```
flask == 2.1.2   
werkzeug==2.1.2
```

**Comment by jgbustos** [comment]
This was an issue in Flask-RESTX, which they fixed in their latest 1.0.3 release
